name: Build containers

on:
  push:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
      - name: Build the container
        run: make build
      #- name: Setup BATS
      #  uses: mig4/setup-bats@v1
      #  with:
      #    bats-version: 1.2.1
      #- name: Test the container
      #  run: make test
      - name: Login to Docker Hub
        if: github.repository_owner == 'eXistenZNL' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the container to Docker Hub
        if: github.repository_owner == 'eXistenZNL' && github.ref == 'refs/heads/master'
        run: docker push existenz/merge-back:latest
